name: reflectable
version: 2.2.5+1
description: >
  Reflection support based on code generation, using 'capabilities' to
  specify which operations to support, on which objects.
homepage: https://www.github.com/dart-lang/reflectable
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  build:
  build_runner:
  dart_style:
  glob: ^1.2.0
  logging: ^0.11.0
  package_config: ^1.1.0
  path: ^1.6.0
  source_span: ^1.5.0
dev_dependencies:
  build_test:
  pedantic:
  test:
